// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/graphbound/graphbound/examples/quotes-api/internal/http/graph"
	"github.com/graphbound/graphbound/examples/quotes-api/internal/http/graph/generated"
	"github.com/graphbound/graphbound/examples/quotes-api/internal/http/rest"
	"github.com/graphbound/graphbound/examples/quotes-api/internal/quote"
	"github.com/graphbound/graphbound/examples/quotes-api/pkg/yeapi"
	"github.com/graphbound/graphbound/pkg/httpds"
	"github.com/graphbound/graphbound/pkg/log"
	"github.com/graphbound/graphbound/pkg/server"
	"github.com/hellofresh/health-go/v5"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initializeAPI() (*API, func(), error) {
	config, err := ProvideConfig()
	if err != nil {
		return nil, nil, err
	}
	clientURL := config.YeAPIURL
	appEnvironment := config.AppEnvironment
	sugaredLogger, cleanup, err := log.ProvideLogger(appEnvironment)
	if err != nil {
		return nil, nil, err
	}
	tracerProvider := yeapi.ProvideTracerProvider(appEnvironment)
	v := _wireValue
	client := yeapi.ProvideClient(clientURL, sugaredLogger, tracerProvider, v...)
	getQuoteUseCase := quote.ProvideGetQuoteUseCase(client, sugaredLogger)
	quoteController := rest.ProvideQuoteController(getQuoteUseCase, sugaredLogger)
	serverTracerProvider, cleanup2, err := server.ProvideTracerProvider(appEnvironment)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	version := _wireVersionValue
	healthCheck := yeapi.ProvideClientHealthCheck(clientURL)
	v2 := ProvideHealthChecks(healthCheck)
	resolver := graph.ProvideResolver(getQuoteUseCase)
	generatedConfig := generated.Config{
		Resolvers: resolver,
	}
	executableSchema := generated.NewExecutableSchema(generatedConfig)
	engine := server.NewGraphQLServer(sugaredLogger, serverTracerProvider, version, v2, executableSchema)
	api, err := ProvideAPI(quoteController, engine, sugaredLogger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return api, func() {
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireValue        = []httpds.Plugin(nil)
	_wireVersionValue = server.Version("1.0.0")
)

// wire.go:

type API struct {
	quoteController rest.QuoteController[gin.Context]
	router          *gin.Engine
	logger          *zap.SugaredLogger
}

func ProvideAPI(
	quoteController rest.QuoteController[gin.Context],
	router *gin.Engine,
	logger *zap.SugaredLogger,
) (*API, error) {
	if logger == nil {
		return nil, fmt.Errorf("ProvideAPI: logger is nil")
	}

	return &API{
		quoteController: quoteController,
		router:          router,
		logger:          logger,
	}, nil
}

func ProvideHealthChecks(
	yeAPIHealthCheck yeapi.HealthCheck,
) []health.Config {
	return []health.Config{
		(health.Config)(yeAPIHealthCheck),
	}
}
